---
 - hosts: webservers
   name: This playbook will install, cofigure and start apache tomcat
   vars:
     - java: java-1.8.0-openjdk-devel

   tasks:
    - name: To install the Java dependency
      yum:
        name: "{{ java }}"
        state: installed

    - name: To download the Apache tomcat
      get_url:
        url: http://mirrors.estointernet.in/apache/tomcat/tomcat-8/v8.5.37/bin/apache-tomcat-8.5.37.tar.gz
        owner: root
        group: root
        mode: 0644
        dest: /opt/apache-tomcat-8.5.37.tar.gz
        timeout: 15
        backup: yes

    - name: To unzip the Tomcat package
      unarchive:
        src: /opt/apache-tomcat-8.5.37.tar.gz
        dest: /opt/
        remote_src: yes
        owner: root
        group: root
        mode: 0744

    - name: To pull a file from remote servers
      fetch:
        src: /opt/apache-tomcat-8.5.37/conf/server.xml
        dest: /opt/

    - name: To update the tomcat server.xml
      copy:
        src: /opt/playbooks/server.xml
        dest: /opt/apache-tomcat-8.5.37/conf/

    - name: To start my apache tomcat
      command: nohup /opt/apache-tomcat-8.5.37/bin/startup.sh
